# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Carlson_RF_ <- function(xr, yr, zr, err) {
    .Call(`_Carlson_Carlson_RF_`, xr, yr, zr, err)
}

Carlson_RD_ <- function(xr, yr, zr, err) {
    .Call(`_Carlson_Carlson_RD_`, xr, yr, zr, err)
}

Carlson_RJ_ <- function(xr, yr, zr, pr, err) {
    .Call(`_Carlson_Carlson_RJ_`, xr, yr, zr, pr, err)
}

